import "/var/www/vhosts/soundjaeger.com/class.soundjaeger.com/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/base.css"
import "/var/www/vhosts/soundjaeger.com/class.soundjaeger.com/my-docs/node_modules/@vuepress/plugin-shiki/lib/client/styles/shiki.css"
import "/var/www/vhosts/soundjaeger.com/class.soundjaeger.com/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/line-numbers.css"
import "/var/www/vhosts/soundjaeger.com/class.soundjaeger.com/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/notation-highlight.css"
import "/var/www/vhosts/soundjaeger.com/class.soundjaeger.com/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/code-block-title.css"